#include "minecraft/mcworld_reader.hpp"
#include "minecraft/mcworld_archive.hpp"
#include <cstring>
namespace pvr::minecraft { namespace { struct Cursor{const std::vector<std::uint8_t>&b;std::size_t p=0;bool take(void*d,std::size_t n){if(p+n>b.size())return false;std::memcpy(d,b.data()+p,n);p+=n;return true;}template<class T>bool scalar(T&v){return take(&v,sizeof(T));}}; void err(std::vector<MinecraftDiagnostic>&d,std::string s,std::string m){d.push_back({MinecraftDiagnosticSeverity::Error,std::move(s),std::move(m),false});}}
bool MinecraftReadResult::ok()const noexcept{for(auto&d:diagnostics)if(d.severity==MinecraftDiagnosticSeverity::Error)return false;return !data.chunks.empty();}
MinecraftReadResult MinecraftWorldReader::read(const std::filesystem::path&path){MinecraftReadResult r;std::vector<MinecraftArchiveEntry>e;if(!MinecraftArchiveReader::read(path,e,r.diagnostics))return r;const MinecraftArchiveEntry*meta=nullptr,*terrain=nullptr;for(auto&x:e){if(x.path=="pvr/metadata.bin")meta=&x;if(x.path=="pvr/terrain.bin")terrain=&x;}if(!meta){err(r.diagnostics,"pvr/metadata.bin","missing critical world metadata");return r;}if(!terrain){err(r.diagnostics,"pvr/terrain.bin","missing critical terrain data");return r;}
 Cursor mc{meta->data};char mm[8]{};if(!mc.take(mm,8)||std::memcmp(mm,"PVRMCMD1",8)){err(r.diagnostics,"pvr/metadata.bin","invalid metadata magic");return r;}std::uint32_t nl=0;if(!mc.scalar(nl)||nl>4096||mc.p+nl>meta->data.size()){err(r.diagnostics,"pvr/metadata.bin","invalid world name");return r;}r.data.metadata.worldName.assign((char*)meta->data.data()+mc.p,nl);mc.p+=nl;if(!mc.scalar(r.data.metadata.seed)||!mc.scalar(r.data.metadata.sectionSize)||!r.data.metadata.sectionSize||r.data.metadata.sectionSize>64){err(r.diagnostics,"pvr/metadata.bin","invalid world metadata values");return r;}std::uint32_t dl=0;if(!mc.scalar(dl)||dl>64||mc.p+dl>meta->data.size()){err(r.diagnostics,"pvr/metadata.bin","invalid dimension name");return r;}r.data.metadata.dimensions.emplace_back((char*)meta->data.data()+mc.p,dl);mc.p+=dl;
 Cursor tc{terrain->data};char tm[8]{};if(!tc.take(tm,8)||std::memcmp(tm,"PVRMCTR1",8)){err(r.diagnostics,"pvr/terrain.bin","invalid terrain magic");return r;}std::uint32_t cc=0;if(!tc.scalar(cc)||cc==0||cc>1000000){err(r.diagnostics,"pvr/terrain.bin","invalid chunk count");return r;}r.data.chunks.reserve(cc);for(std::uint32_t ci=0;ci<cc;++ci){MinecraftChunkRecord c;std::uint32_t dl2=0,sc=0;if(!tc.scalar(c.x)||!tc.scalar(c.z)||!tc.scalar(dl2)||dl2>64||tc.p+dl2>terrain->data.size()){err(r.diagnostics,"pvr/terrain.bin","truncated chunk header");return r;}c.dimension.assign((char*)terrain->data.data()+tc.p,dl2);tc.p+=dl2;if(!tc.scalar(sc)||sc>4096){err(r.diagnostics,"pvr/terrain.bin","invalid section count");return r;}c.sections.reserve(sc);for(std::uint32_t si=0;si<sc;++si){MinecraftSectionRecord s;std::uint32_t bc=0;if(!tc.scalar(s.y)||!tc.scalar(bc)||bc>1048576){err(r.diagnostics,"pvr/terrain.bin","truncated section header");return r;}s.blocks.reserve(bc);for(std::uint32_t bi=0;bi<bc;++bi){MinecraftBlockStateRecord b;if(!tc.scalar(b.x)||!tc.scalar(b.y)||!tc.scalar(b.z)||!tc.scalar(b.sourceStateId)){err(r.diagnostics,"pvr/terrain.bin","truncated block record");return r;}if(b.x>=r.data.metadata.sectionSize||b.y>=r.data.metadata.sectionSize||b.z>=r.data.metadata.sectionSize){err(r.diagnostics,"pvr/terrain.bin","block coordinate outside section");return r;}s.blocks.push_back(b);}c.sections.push_back(std::move(s));}r.data.chunks.push_back(std::move(c));}return r;}
}
